### ISSUE TITLE
maxed out the number of file descriptor

### ISSUE THREAD

**Issue by arash009** [PegaSysEng/web3signer#153]
Teku can not sign using eth2signer and the number of socket file descriptior has rocketed to 28287
```
[magicking@broken:~/.local/share/teku/logs]$ sudo ls -l /proc/608/fd | grep socket | wc -l
28287 # Teku number of socket file descriptor
[magicking@broken:~/teku]$ sudo ls -l /proc/6740/fd | grep socket | wc -l
27304 # Eth2signer number of socket file descriptor
```

```
2020-08-06 01:07:08.841+02:00 | ForkJoinPool.commonPool-worker-7 | ERROR | teku-validator-log | ESC[31mValidator   *** Failed to produce attestation  Slot: 10235ESC[0m
tech.pegasys.teku.validator.client.signer.ExternalSignerException: External signer failed to sign due to java.net.ConnectException: Cannot assign requested address
        at tech.pegasys.teku.validator.client.signer.ExternalMessageSignerService.getBlsSignature(ExternalMessageSignerService.java:107) ~[teku-validator-client-0.12.3-SNAPSHOT.jar:0.12.3-dev-6d03cc54]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) [?:?]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907) [?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
Caused by: java.util.concurrent.CompletionException: java.net.ConnectException: Cannot assign requested address
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1185) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:345) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:250) ~[java.net.http:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1776) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
Caused by: java.net.ConnectException: Cannot assign requested address
        at jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1015) ~[java.net.http:?]
        at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:179) ~[java.net.http:?]
        at jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Http1Exchange.java:237) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$8(Exchange.java:422) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.checkFor407(Exchange.java:354) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Exchange.java:426) ~[java.net.http:?]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
        at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2337) ~[?:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:426) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:330) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:322) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:304) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:250) ~[java.net.http:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1776) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
Caused by: java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:476) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:468) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694) ~[?:?]
        at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:165) ~[java.net.http:?]
        at java.security.AccessController.doPrivileged(AccessController.java:552) ~[?:?]
        at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:167) ~[java.net.http:?]
        at jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Http1Exchange.java:237) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$8(Exchange.java:422) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.checkFor407(Exchange.java:354) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Exchange.java:426) ~[java.net.http:?]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
        at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2337) ~[?:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:426) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:330) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:322) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:304) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:250) ~[java.net.http:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1776) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
2020-08-06 01:07:08.845+02:00 | ForkJoinPool.commonPool-worker-7 | ERROR | teku-validator-log | ESC[31mValidator   *** Failed to produce attestation  Slot: 10235ESC[0m
[...]
```

**Comment by MadelineMurray** [comment]
@rain-on - does this have doc impacts?  If so, it's not clear to me what they are? If not, should this be moved back to In Progress or Closed?

**Comment by rain-on** [comment]
Yup - so this REMOVES the "--key-cache-size" command line argument from Eth2Signer - there is no limit to the key cache, we now load ALL keys into memory.
